//用户信息
const SET_PHONE = 'SET_PHONE';
const SET_EMAIL = 'SET_EMAIL';
const SET_USERNAME = 'SET_USERNAME';
const SET_AVATAR_URL = 'SET_AVATAR_URL';
const SET_BIRTHDAY = 'SET_BIRTHDAY';
const SET_CITY = 'SET_CITY';
const SET_FOLLOWEDS = 'SET_FOLLOWEDS';
const SET_FOLLOWS = 'SET_FOLLOWS';
const SET_GENDER = 'SET_GENDER';
const SET_NICKNAME = 'SET_NICKNAME';
const SET_PROVINCE = 'SET_PROVINCE';
const SET_PLAY_LIST_COUNT = 'SET_PLAY_LIST_COUNT';
const SET_BACKGROUND_URL = 'SET_BACKGROUND_URL';
const SET_LEVEL = 'SET_LEVEL';
const SET_COLLECTED_MENUS = 'SET_COLLECTED_MENUS';
const SET_CREATED_MENUS = 'SET_CREATED_MENUS';
const SET_PLATLIST = 'SET_PLATLIST';
const SET_LIKELIST = 'SET_LIKELIST';
const SET_LISTEN_SONGS = 'SET_LISTEN_SONGS';
const SET_CREATE_TIME = 'SET_CREATE_TIME';
const SET_PLAYING_SONG = 'SET_PLAYING_SONG';
const SET_PLAYING_LIST = 'SET_PLAYING_LIST';
const SET_PLAYING_TIMER = 'SET_PLAYING_TIMER';
const SET_PLAYING_TYPE = 'SET_PLAYING_TYPE';
const SET_PLAYER = 'SET_PLAYER';
const SET_LYRIC_NOW = 'SET_LYRIC_NOW';
const SET_CURRENT_TIME = 'SET_CURRENT_TIME';
const SET_LYRICS = 'SET_LYRICS';

//身份验证信息
const SET_USER_ID = 'SET_USER_ID';
const SET_IS_LOGIN = 'SET_IS_LOGIN';
const SET_TOKEN = 'SET_TOKEN';

export {
    SET_LYRICS,
    SET_CURRENT_TIME,
    SET_LYRIC_NOW,
    SET_PLAYER,
    SET_PLAYING_TIMER,
    SET_PLAYING_TYPE,
    SET_PLAYING_SONG,
    SET_PLAYING_LIST,
    SET_CREATE_TIME,
    SET_LISTEN_SONGS,
    SET_LIKELIST,
    SET_CREATED_MENUS,
    SET_PLATLIST,
    SET_PHONE,
    SET_EMAIL,
    SET_USERNAME,
    SET_USER_ID,
    SET_IS_LOGIN,
    SET_AVATAR_URL,
    SET_BIRTHDAY,
    SET_CITY,
    SET_FOLLOWEDS,
    SET_FOLLOWS,
    SET_GENDER,
    SET_NICKNAME,
    SET_PROVINCE,
    SET_TOKEN,
    SET_PLAY_LIST_COUNT,
    SET_BACKGROUND_URL,
    SET_LEVEL,
    SET_COLLECTED_MENUS
}