//用户信息
const SET_PHONE = 'SET_PHONE';
const SET_USERNAME = 'SET_USERNAME';
const SET_USER_ID = 'SET_USER_ID';
const SET_AVATAR_URL = 'SET_AVATAR_URL';
const SET_BIRTHDAY = 'SET_BIRTHDAY';
const SET_CITY = 'SET_CITY';
const SET_FOLLOWEDS = 'SET_PHONE';
const SET_FOLLOWS = 'SET_PHONE';
const SET_GENDER = 'SET_GENDER';
const SET_NICKNAME = 'SET_NICKNAME';
const SET_PROVINCE = 'SET_PROVINCE';

//身份验证信息
const SET_IS_LOGIN = 'SET_IS_LOGIN';
const SET_TOKEN = 'SET_TOKEN';

export {
    SET_PHONE,
    SET_USERNAME,
    SET_USER_ID,
    SET_IS_LOGIN,
    SET_AVATAR_URL,
    SET_BIRTHDAY,
    SET_CITY,
    SET_FOLLOWEDS,
    SET_FOLLOWS,
    SET_GENDER,
    SET_NICKNAME,
    SET_PROVINCE,
    SET_TOKEN
}